on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: Microsoft Windows Server 2022

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip shell: C:\Program Files\PowerShell\7\pwsh.EXE 
    - name: Extract
      run: Expand-Archive ngrok.zip shell: C:\Program Files\PowerShell\7\pwsh.EXE
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN shell: C:\Program Files\PowerShell\7\pwsh.EXE
      env:
        NGROK_AUTH_TOKEN: ${{ 2BgtzrkC9PkHgnspg9kwU9DJ1LS_3A5p4aqYS9Nm7TPRemWgG }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0 shell: C:\Program Files\PowerShell\7\pwsh.EXE
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop" shell: C:\Program Files\PowerShell\7\pwsh.EXE
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force) shell: C:\Program Files\PowerShell\7\pwsh.EXE
    - name: Create Tunnel
       run: sc start ngrok
    - name: Connect to your RDP 2core-7GB Ram.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: cmd /c loop.bat
